{
 "title": "nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nuts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Transaction Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Tx/s" } },
   "targets": [
    {
     "expr": "rate(nuts_dag_transactions_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transactions Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Tx" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nuts_dag_transactions_total", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Metric Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scrape_duration_seconds[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth0|lo\"}[1m])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=~\"eth0|lo\"}[1m])",
     "legendFormat": "receive {{instance}} {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{device=~\"eth0|lo\"}[1m])",
     "legendFormat": "transmit {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0|lo\"}[1m])",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Time Rate",
   "type": "timeseries",
   "description": "CPU seconds per second. max == num cpus",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{instance}} process_"
    },
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode=\"system\"}[1m]))",
     "legendFormat": "{{instance}} node_:system"
    },
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode=\"user\"}[1m]))",
     "legendFormat": "{{instance}} node_:user"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sockets Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_sockstat_sockets_used{}", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Disk IO Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_open_fds{}", "legendFormat": "{{instance}} {{__name__}}" },
    { "expr": "node_filefd_allocated{}", "legendFormat": "{{instance}} {{__name__}}" }
   ]
  },
  {
   "title": "Disk Write Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_write_time_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_read_time_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Flush Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_flush_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(go_memstats_heap_released_bytes[1m])",
     "legendFormat": "{{instance}} released"
    },
    {
     "expr": "avg_over_time(go_memstats_heap_alloc_bytes[1m])",
     "legendFormat": "{{instance}} alloc"
    },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "{{instance}} sys" }
   ]
  },
  {
   "title": "Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_stack_sys_bytes{}", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}