global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: node1
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'node1:1323'
        - 'node1:9100'
  - job_name: node2
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'node2:1323'
        - 'node2:9100'
