networks:
  default:
    name: performance-monitor
    external: true

name: performance-test-network
services:
  ##### TEST CONFIGURATION #####
  artillery:
    image: artilleryio/artillery:latest
    depends_on:
      nodeA:
        condition: service_healthy
    volumes: ["../../artillery:/scripts:ro"]
    command: run /scripts/private-vcs.yaml
  # This container exposes the docker rest api (https://docs.docker.com/engine/api/) on http://docker.api to other containers.
  socat:
    image: bobrik/socat
    hostname: docker.api # give it an interpretable hostname
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"]
    command: TCP-LISTEN:80,fork UNIX-CONNECT:/var/run/docker.sock

  ##### TEST NETWORK SETUP #####
  # must contain at least a nodeA and nodeB
  nodeA:
    container_name: nodeA  # used as docker container ID in artillery
    image: &image nutsfoundation/nuts-node:dev
    depends_on: [redisA]
    environment:
      NUTS_STORAGE_REDIS_ADDRESS: "redisA:6379"
    volumes: ["../nuts.yaml:/nuts.yaml:ro"]
    ports:
      - "11323:1323"
    healthcheck:
      interval: 5s
  nodeB:
    container_name: nodeB
    image: *image
    depends_on: [redisB]
    environment:
      NUTS_STORAGE_REDIS_ADDRESS: "redisB:6379"
    volumes: ["../nuts.yaml:/nuts.yaml:ro"]

  redisA:
    image: redis:7
    volumes:
      - "./redis.conf:/run/redis.conf:ro"
    command: redis-server /run/redis.conf

  redisB:
    image: redis:7
    volumes:
      - "./redis.conf:/run/redis.conf:ro"
    command: redis-server /run/redis.conf

  redis_exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: "" # prevents scraping attempt on localhost, actual scape configs can be found in prometheus.yml
