global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: nodeA
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'nodeA:1323'
        - 'nodeA:9100'
  - job_name: nodeB
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'nodeB:1323'
        - 'nodeB:9100'

# Redis
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: redis_exporter_targets
    static_configs:
      - targets: # add all redis instances here
          - redis://redis:6379
          - redis://redisA:6379
          - redis://redisB:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121
  ## config for scraping the exporter itself
  - job_name: redis_exporter
    static_configs:
      - targets:
          - redis_exporter:9121